### ISSUE TITLE
Minor documentation note

### ISSUE THREAD

**Issue by ghost** [wcascades/ssgn#1]
Hi, thanks for making this.  I will use it.

A minor note for the documentation (not even worth creating a PR):
The custom location set by `g:SSGNNoteDirectory` must end with a forward slash (as per the example), or else it will create a file instead of the intended directory.  Could this be explicitly stated in the documentation?

**Comment by Wiebesiek** [comment]
I'll get right on it! Thank you for checking it out.

**Comment by Wiebesiek** [comment]
Updated!
